/* Auto-generated by admin-upload.html — 2026-09-26T01:59:54.316Z */
window.SMARTSTUDENT_CATALOGUE = [
  {
    "id": "pdf-1790387987059-oukoh",
    "title": "Science 6 Unit",
    "subject": "Science",
    "category": "Exercises",
    "language": "தமிழ்",
    "description": "Science Grade 09 unit exam",
    "uploadDate": "2026-09-26",
    "status": "published",
    "fileUrl": "https://drive.google.com/file/d/1q4RscRnQCvxqkWykM8Deb61WV0w-mxVg/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1q4RscRnQCvxqkWykM8Deb61WV0w-mxVg",
    "pages": 0,
    "driveFileId": "1q4RscRnQCvxqkWykM8Deb61WV0w-mxVg"
  }
];
